# docker-compose.yml
version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/api_data.db
      - SECRET_KEY=${SECRET_KEY}
      - ADMIN_SECRET_KEY=${ADMIN_SECRET_KEY}
    restart: unless-stopped
